// Property 14: TOTP Code Format
// Verify code is exactly 6 decimal digit characters
// Validates: Requirements 6.1

import XCTest
import SwiftCheck
@testable import BrightPassKit

/// Generator for valid 6-digit TOTP codes (what a conforming API returns).
private let digitChars: [Character] = Array("0123456789")
private let arbTotpDigitCode: Gen<String> = Gen.compose { c in
    let digits = (0..<6).map { _ in c.generate(using: Gen<Character>.fromElements(of: digitChars)) }
    return String(digits)
}

/// Generator for remaining seconds in a TOTP period.
private let arbRemainingSeconds: Gen<Int> = Int.arbitrary.map { abs($0) % 30 + 1 }

/// Mock API client that returns TOTP codes generated by the property test framework.
private final class TOTPMockAPIClient: APIClientProtocol, @unchecked Sendable {
    var nextCode: String = "000000"
    var nextRemaining: Int = 30

    func generateTOTP(secret: String) async throws -> TotpCode {
        TotpCode(code: nextCode, remainingSeconds: nextRemaining, period: 30)
    }

    func validateTOTPSecret(secret: String) async throws -> TotpCode {
        TotpCode(code: nextCode, remainingSeconds: nextRemaining, period: 30)
    }

    // MARK: - Unused stubs
    func requestDirectLogin() async throws -> DirectLoginChallenge { fatalError() }
    func submitDirectChallenge(challenge: String, signature: String, username: String?, email: String?) async throws -> DirectChallengeResponse { fatalError() }
    func refreshToken() async throws -> DirectChallengeResponse { fatalError() }
    func logout() async throws { fatalError() }
    func verifyToken() async throws -> UserProfile { fatalError() }
    func login(username: String, password: String) async throws -> AuthResponse { fatalError() }
    func register(username: String, email: String, password: String) async throws -> AuthResponse { fatalError() }
    func listVaults() async throws -> [VaultMetadata] { fatalError() }
    func createVault(name: String, masterPassword: String) async throws -> VaultMetadata { fatalError() }
    func openVault(id: String, masterPassword: String) async throws -> DecryptedVault { fatalError() }
    func deleteVault(id: String) async throws { fatalError() }
    func renameVault(id: String, name: String) async throws -> VaultMetadata { fatalError() }
    func listEntries(vaultId: String) async throws -> [EntryPropertyRecord] { fatalError() }
    func getEntry(vaultId: String, entryId: String) async throws -> VaultEntry { fatalError() }
    func createEntry(vaultId: String, entry: VaultEntry) async throws -> VaultEntry { fatalError() }
    func updateEntry(vaultId: String, entryId: String, entry: VaultEntry) async throws -> VaultEntry { fatalError() }
    func deleteEntry(vaultId: String, entryId: String) async throws { fatalError() }
    func searchEntries(vaultId: String, query: String) async throws -> [EntryPropertyRecord] { fatalError() }
    func generatePassword(options: PasswordOptions) async throws -> GeneratedPassword { fatalError() }
    func checkBreach(password: String) async throws -> BreachCheckResult { fatalError() }
    func autofillLookup(serviceIdentifier: String) async throws -> [AutofillPayload] { fatalError() }
    func getAuditLog(vaultId: String) async throws -> [AuditLogEntry] { fatalError() }
    func shareVault(vaultId: String, memberId: String, permission: SharePermission) async throws { fatalError() }
    func revokeShare(vaultId: String, memberId: String) async throws { fatalError() }
    func listSharedMembers(vaultId: String) async throws -> [SharedMember] { fatalError() }
    func configureEmergencyAccess(vaultId: String, config: EmergencyAccessConfig) async throws { fatalError() }
    func getEmergencyAccessConfig(vaultId: String) async throws -> EmergencyAccessConfig { fatalError() }
    func recoverVault(vaultId: String, shares: [String]) async throws -> DecryptedVault { fatalError() }
    func importEntries(vaultId: String, source: ImportSource, fileData: Data) async throws -> ImportResult { fatalError() }
    func changeMasterPassword(vaultId: String, currentPassword: String, newPassword: String) async throws { fatalError() }
    func exportEntries(vaultId: String, format: ExportFormat) async throws -> Data { fatalError() }
}

/// Synchronously fetches a TOTP code from the mock API client using a detached task
/// to avoid MainActor deadlock.
private func fetchTOTPCodeSync(code: String, remaining: Int) -> String? {
    let mock = TOTPMockAPIClient()
    mock.nextCode = code
    mock.nextRemaining = remaining
    nonisolated(unsafe) var result: String?
    let semaphore = DispatchSemaphore(value: 0)
    Task.detached {
        let totpCode = try await mock.generateTOTP(secret: "JBSWY3DPEHPK3PXP")
        result = totpCode.code
        semaphore.signal()
    }
    semaphore.wait()
    return result
}

@available(macOS 14.0, iOS 17.0, *)
final class TOTPCodeFormatPropertyTests: XCTestCase {

    /// Property 14: TOTP Code Format — code is exactly 6 decimal digit characters.
    func testTOTPCodeIsExactlySixDecimalDigits() {
        property("TOTP code is exactly 6 decimal digits") <- forAllNoShrink(arbTotpDigitCode, arbRemainingSeconds) {
            (code: String, remaining: Int) in
            guard let received = fetchTOTPCodeSync(code: code, remaining: remaining) else {
                return false
            }
            let isLength6 = received.count == 6
            let allDigits = received.allSatisfy { $0.isNumber && $0.isASCII }
            return isLength6 && allDigits
        }
    }
}
